# Generated by Django 3.1 on 2020-08-09 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoBlogApp', '0003_post_post_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='meta_description',
            field=models.CharField(default='Default Meta Description', max_length=255),
        ),
    ]
